### PR TITLE
#55 - Multiple application to topic by the same user are allowed

### PR DESCRIPTION
**Pull request by TheSprtCz**
# Overview
* Applicant is now unique for each topic.
* If student is already applied, there will be Your Application button, which redirects him to his application, instead of Apply button.
* Added Integration Test class for testing ApplicationController.
* Added new database migration script.

# Changes in files
**TestBootStrap.groovy**
* Updated testing applications to follow one application per user rule.

**TopicController.groovy**
* Added check for existing application.

**Application.groovy**
* Made **applicant** unique to **topic**.

**topic/show.bsp**
* Changed Apply to Your Application button, when user is already applied.

**ApplicationIntegrationSpec.groovy**
 * New Integration Test for Application Controller

### CODE REVIEW

**Comment by VaclavDedik** [comment]
Looks good :)

**Comment by VaclavDedik** [comment]
Verified. Merging, thanks!

**Comment by VaclavDedik** [comment]
Unfortunately, I had to revert this change for now. There is a problem that came up when deploying. Some applications with unique combination of applicant_id and topic_id are twice in the database for a good reason - first application was declined and only the second one was approved. So my suggestion would be to remove the unique id constraint (including the database migration) and just check for duplicate application_id and topic_id that is still pending or approved (and not declined) on the application level, not in the database.

**Comment by TheSprtCz** [comment]
Ok, so expected behavior is to forbid users who have pending Application to apply for more?

**Comment by VaclavDedik** [comment]
Yes, that's correct.

**Comment by TheSprtCz** [comment]
* Updated behavior to forbid only users, who have pending Application.
  * Users, who have already accepted Application, will see 'Show your Thesis' button.
  * Users, who have pending Application, will see 'Show your Application' button.
* Removed NotificationIntegrationSpec, because it was colliding with ApplicationController test.
  * These tests collided even when DB was cleared after the test.
  * Both works separately
* Removed destroy() closure from BootStrap because it wasn't working anymore (even when I changed database name)

**Comment by VaclavDedik** [comment]
Verified. Merging, thanks!

**Pull request closed without merging**
