### PR TITLE
#122 - Changed 'supervisor' to 'Academic Supervisor' and 'leader' to 'Technical Leader'

### PR DESCRIPTION
**Pull request by TheSprtCz**
I changed only English localization, because Czech already has 'Vedoucí' a 'Vedoucí na Univerzitě', which should be descriptive enough.

### CODE REVIEW

**Comment by sbunciak** [comment]
I'd rather have 'Technický vedoucí' in Czech than just 'Vedoucí'.

**Comment by jcechace** [comment]
Agreed, let's keep these terms consistent

Technical lead - Technicky Vedouci
Academic lead - Universitni vedouci ("Akademicky vedouci" sounds a bit weird in Czech).

**Comment by jcechace** [comment]
@sbunciak I was informed that the original terms "Academic Supervisor" and "Technical Leader" were agreed upon yesterday. However I'd still like to propose the terms mentioned above. 

Whether a we use leader or lead is probably not important (afaik the term "leader" has a more formal and authoritative connotation) 

What's important is that we get completely rid of the choice between "leader" and "supervisor" and instead simply have 2 different types of the same role.  So maybe "Technical supervisor" and "Academic supervisor" could work better

**Comment by sbunciak** [comment]
I was told that in the academic space they are used to term "supervisor". That's why we agreed on using Academic Supervisor. 
I have no preference over technical supervisor vs. technical leader. Both of them will work I guess.

**Comment by TheSprtCz** [comment]
Changed 'vedoucí' to 'Technický vedoucí' and 'vedoucí z univerzity' to 'Univerzitní vedoucí'.

**Comment by VaclavDedik** [comment]
Verified & merged, thanks!

**Pull request closed without merging**
